title: Noir
description: >- # this means to ignore newlines until "baseurl:"
  Noir is an attack surface detector form source code.
baseurl: "/docs" 
url: ""
repository: noir-cr/noir
theme: just-the-docs

plugins:
  - jekyll-feed

logo: "/assets/images/noir.png"
favicon_ico: "/assets/images/noir.png"
color_scheme: dark

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

aux_links:
  "GitHub":
    - "https://github.com/noir-cr/noir"

nav_external_links:
  - title: Noir on GitHub
    url: https://github.com/noir-cr/noir

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
